<script setup>
import { ref } from 'vue'
import RiskBadge from '../components/RiskBadge.vue'
import EmptyState from '../components/EmptyState.vue'
import { computeSensorFeatures, computeSensorFeaturesFile, analyzeSensors } from '../api'
const emit = defineEmits(['record']); const csvFile = ref(null); const rowsText = ref(''); const stage = ref(''); const workType = ref(''); const city = ref(''); const features = ref(null); const result = ref(null); const loading = ref(false); const error = ref('')
function chooseCsv(event) { csvFile.value = event.target.files?.[0] || null }
function parseRows() { return rowsText.value.split('\n').filter(Boolean).map(line => { const [TIME, TSP, NOISE, TEMP, HUM, PM10] = line.split(',').map(v => v.trim()); return { TIME, TSP: Number(TSP), NOISE: Number(NOISE), TEMP: Number(TEMP), HUM: Number(HUM), PM10: Number(PM10) } }) }
async function run() { loading.value = true; error.value = ''; try { const context = { stage: stage.value, work_type: workType.value, city: city.value }; features.value = csvFile.value ? await computeSensorFeaturesFile(csvFile.value, context) : await computeSensorFeatures(parseRows(), context); result.value = await analyzeSensors(features.value, context, true); emit('record', { type: '传感器研判', title: result.value?.overall?.headline || '传感器研判完成', risk: result.value?.overall?.risk_level || 'GREEN' }) } catch (e) { error.value = e.message } finally { loading.value = false } }
</script>
<template><section class="view-section"><div class="view-heading"><div><p class="eyebrow">传感器 / 03</p><h2>让时序数据说话。</h2><p class="lede">把现场测量转换成阈值、趋势和可执行的处置建议。</p></div><RiskBadge :level="result?.overall?.risk_level || 'GREEN'" /></div><div class="split-layout"><form class="panel form-panel" @submit.prevent="run"><label class="upload-zone compact"><input type="file" accept=".csv,text/csv" @change="chooseCsv" /><span class="upload-icon">+</span><strong>{{ csvFile ? csvFile.name : '上传 CSV 时序文件' }}</strong><small>也可以在下方粘贴 CSV 数据</small></label><textarea v-model="rowsText" placeholder="TIME,TSP,NOISE,TEMP,HUM,PM10&#10;2026-09-22 08:00,0.3,72,31,58,0.2"></textarea><div class="form-grid"><label>施工阶段<input v-model="stage" placeholder="例如：土方/地基处理" /></label><label>城市<input v-model="city" placeholder="例如：西安" /></label></div><label>作业类型<input v-model="workType" placeholder="例如：土方开挖" /></label><button class="primary-button" :disabled="loading">{{ loading ? '计算中...' : '计算并研判' }}</button><p v-if="error" class="error-text">{{ error }}</p></form><article class="panel result-panel"><div v-if="result"><p class="eyebrow">分析结果</p><div class="result-header"><h3>传感器风险研判</h3><RiskBadge :level="result.overall?.risk_level || 'GREEN'" /></div><ul class="finding-list"><li v-for="warning in result.warnings || []" :key="warning.metric"><RiskBadge :level="warning.level" /><div><strong>{{ warning.title }}</strong><p>{{ warning.detail }}</p></div></li></ul></div><EmptyState v-else title="等待时序数据" message="上传 CSV 或粘贴数据后开始分析。" /></article></div></section></template>
